/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIdRouteImport } from './routes/auth.$id'
import { Route as TodosRouteImport } from './routes/_.todos'
import { Route as ApiUploadSplatRouteImport } from './routes/api/upload.$'
import { Route as ApiElectricSplatRouteImport } from './routes/api/electric.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIdRoute = AuthIdRouteImport.update({
  id: '/auth/$id',
  path: '/auth/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosRoute = TodosRouteImport.update({
  id: '/_/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadSplatRoute = ApiUploadSplatRouteImport.update({
  id: '/api/upload/$',
  path: '/api/upload/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElectricSplatRoute = ApiElectricSplatRouteImport.update({
  id: '/api/electric/$',
  path: '/api/electric/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/todos': typeof TodosRoute
  '/auth/$id': typeof AuthIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/electric/$': typeof ApiElectricSplatRoute
  '/api/upload/$': typeof ApiUploadSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/todos': typeof TodosRoute
  '/auth/$id': typeof AuthIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/electric/$': typeof ApiElectricSplatRoute
  '/api/upload/$': typeof ApiUploadSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_/todos': typeof TodosRoute
  '/auth/$id': typeof AuthIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/electric/$': typeof ApiElectricSplatRoute
  '/api/upload/$': typeof ApiUploadSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/todos'
    | '/auth/$id'
    | '/api/auth/$'
    | '/api/electric/$'
    | '/api/upload/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/todos'
    | '/auth/$id'
    | '/api/auth/$'
    | '/api/electric/$'
    | '/api/upload/$'
  id:
    | '__root__'
    | '/'
    | '/_/todos'
    | '/auth/$id'
    | '/api/auth/$'
    | '/api/electric/$'
    | '/api/upload/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TodosRoute: typeof TodosRoute
  AuthIdRoute: typeof AuthIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiElectricSplatRoute: typeof ApiElectricSplatRoute
  ApiUploadSplatRoute: typeof ApiUploadSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$id': {
      id: '/auth/$id'
      path: '/auth/$id'
      fullPath: '/auth/$id'
      preLoaderRoute: typeof AuthIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_/todos': {
      id: '/_/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/$': {
      id: '/api/upload/$'
      path: '/api/upload/$'
      fullPath: '/api/upload/$'
      preLoaderRoute: typeof ApiUploadSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/electric/$': {
      id: '/api/electric/$'
      path: '/api/electric/$'
      fullPath: '/api/electric/$'
      preLoaderRoute: typeof ApiElectricSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TodosRoute: TodosRoute,
  AuthIdRoute: AuthIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiElectricSplatRoute: ApiElectricSplatRoute,
  ApiUploadSplatRoute: ApiUploadSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
