/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RouteImport } from './routes/_'
import { Route as IndexRouteImport } from './routes/_.index'
import { Route as AuthIdRouteImport } from './routes/auth.$id'
import { Route as SettingsRouteImport } from './routes/_/settings'
import { Route as GraphRouteImport } from './routes/_/graph'
import { Route as ApiUploadSplatRouteImport } from './routes/api/upload.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as NotesNoteIdRouteImport } from './routes/_/notes/$noteId'
import { Route as CanvasCanvasIdRouteImport } from './routes/_/canvas/$canvasId'

const Route = RouteImport.update({
  id: '/_',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Route,
} as any)
const AuthIdRoute = AuthIdRouteImport.update({
  id: '/auth/$id',
  path: '/auth/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => Route,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => Route,
} as any)
const ApiUploadSplatRoute = ApiUploadSplatRouteImport.update({
  id: '/api/upload/$',
  path: '/api/upload/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => Route,
} as any)
const CanvasCanvasIdRoute = CanvasCanvasIdRouteImport.update({
  id: '/canvas/$canvasId',
  path: '/canvas/$canvasId',
  getParentRoute: () => Route,
} as any)

export interface FileRoutesByFullPath {
  '/graph': typeof GraphRoute
  '/settings': typeof SettingsRoute
  '/auth/$id': typeof AuthIdRoute
  '/': typeof IndexRoute
  '/canvas/$canvasId': typeof CanvasCanvasIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/upload/$': typeof ApiUploadSplatRoute
}
export interface FileRoutesByTo {
  '/graph': typeof GraphRoute
  '/settings': typeof SettingsRoute
  '/auth/$id': typeof AuthIdRoute
  '/': typeof IndexRoute
  '/canvas/$canvasId': typeof CanvasCanvasIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/upload/$': typeof ApiUploadSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_': typeof RouteWithChildren
  '/_/graph': typeof GraphRoute
  '/_/settings': typeof SettingsRoute
  '/auth/$id': typeof AuthIdRoute
  '/_/': typeof IndexRoute
  '/_/canvas/$canvasId': typeof CanvasCanvasIdRoute
  '/_/notes/$noteId': typeof NotesNoteIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/upload/$': typeof ApiUploadSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/graph'
    | '/settings'
    | '/auth/$id'
    | '/'
    | '/canvas/$canvasId'
    | '/notes/$noteId'
    | '/api/auth/$'
    | '/api/upload/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/graph'
    | '/settings'
    | '/auth/$id'
    | '/'
    | '/canvas/$canvasId'
    | '/notes/$noteId'
    | '/api/auth/$'
    | '/api/upload/$'
  id:
    | '__root__'
    | '/_'
    | '/_/graph'
    | '/_/settings'
    | '/auth/$id'
    | '/_/'
    | '/_/canvas/$canvasId'
    | '/_/notes/$noteId'
    | '/api/auth/$'
    | '/api/upload/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Route: typeof RouteWithChildren
  AuthIdRoute: typeof AuthIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiUploadSplatRoute: typeof ApiUploadSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_': {
      id: '/_'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_/': {
      id: '/_/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof Route
    }
    '/auth/$id': {
      id: '/auth/$id'
      path: '/auth/$id'
      fullPath: '/auth/$id'
      preLoaderRoute: typeof AuthIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_/settings': {
      id: '/_/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof Route
    }
    '/_/graph': {
      id: '/_/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof Route
    }
    '/api/upload/$': {
      id: '/api/upload/$'
      path: '/api/upload/$'
      fullPath: '/api/upload/$'
      preLoaderRoute: typeof ApiUploadSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_/notes/$noteId': {
      id: '/_/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof Route
    }
    '/_/canvas/$canvasId': {
      id: '/_/canvas/$canvasId'
      path: '/canvas/$canvasId'
      fullPath: '/canvas/$canvasId'
      preLoaderRoute: typeof CanvasCanvasIdRouteImport
      parentRoute: typeof Route
    }
  }
}

interface RouteChildren {
  GraphRoute: typeof GraphRoute
  SettingsRoute: typeof SettingsRoute
  IndexRoute: typeof IndexRoute
  CanvasCanvasIdRoute: typeof CanvasCanvasIdRoute
  NotesNoteIdRoute: typeof NotesNoteIdRoute
}

const RouteChildren: RouteChildren = {
  GraphRoute: GraphRoute,
  SettingsRoute: SettingsRoute,
  IndexRoute: IndexRoute,
  CanvasCanvasIdRoute: CanvasCanvasIdRoute,
  NotesNoteIdRoute: NotesNoteIdRoute,
}

const RouteWithChildren = Route._addFileChildren(RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  Route: RouteWithChildren,
  AuthIdRoute: AuthIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiUploadSplatRoute: ApiUploadSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
